import type { IconComponent } from "./iconSystem";
import {
  ActivityIcon,
  AddIcon,
  AlertTriangleIcon,
  BackIcon,
  BoxIcon,
  BoxesIcon,
  BracesIcon,
  BranchIcon,
  CableIcon,
  ChartLineIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CloseIcon,
  CloudIcon,
  CodeIcon,
  CopyIcon,
  DashboardIcon,
  DatabaseIcon,
  DeleteIcon,
  DragHandleIcon,
  EditIcon,
  ExternalLinkIcon,
  FileTextIcon,
  FunctionIcon,
  GaugeIcon,
  GridIcon,
  HandIcon,
  HomeIcon,
  HorizontalResizeIcon,
  ImageIcon,
  ImagePlaceholderIcon,
  ImagesIcon,
  InboxIcon,
  InfoIcon,
  KeyIcon,
  LayerStackIcon,
  LayersIcon,
  LinkIcon,
  LockIcon,
  MaximizeIcon,
  MenuIcon,
  MinusIcon,
  MonitorIcon,
  MonitorSettingsIcon,
  MoonIcon,
  NetworkIcon,
  NotificationIcon,
  PaletteIcon,
  PanelTopIcon,
  PlayIcon,
  PointerClickIcon,
  PointerIcon,
  RadioIcon,
  RadioTowerIcon,
  RadiusIcon,
  RectangleIcon,
  ResetIcon,
  RowsIcon,
  SaveIcon,
  SearchIcon,
  ServerSettingsIcon,
  SettingsIcon,
  SmartphoneIcon,
  SquareIcon,
  StarIcon,
  SunIcon,
  TabletIcon,
  TagIcon,
  TagsIcon,
  TemplateIcon,
  ThemeIcon,
  TypographyIcon,
  UnlinkIcon,
  UploadIcon,
  VerticalResizeIcon,
  WorkflowIcon,
  ZapIcon
} from "./iconComponents";

export type IconCategory = "Actions" | "Navigation" | "Data & runtime" | "Editor & layout" | "Appearance" | "Media & devices" | "Status & misc";

export type IconCatalogEntry = {
  name: string;
  source: string;
  category: IconCategory;
  component: IconComponent;
};

/** Public icon inventory used by documentation and Storybook. */
export const editorIconCatalog: readonly IconCatalogEntry[] = [
  { name: "Add", source: "Plus", category: "Actions", component: AddIcon },
  { name: "Delete", source: "Trash2", category: "Actions", component: DeleteIcon },
  { name: "Edit", source: "Pencil", category: "Actions", component: EditIcon },
  { name: "Copy", source: "Copy", category: "Actions", component: CopyIcon },
  { name: "Save", source: "Save", category: "Actions", component: SaveIcon },
  { name: "Reset", source: "RotateCcw", category: "Actions", component: ResetIcon },
  { name: "Close", source: "X", category: "Actions", component: CloseIcon },
  { name: "Check", source: "Check", category: "Actions", component: CheckIcon },
  { name: "Back", source: "ArrowLeft", category: "Actions", component: BackIcon },
  { name: "ExternalLink", source: "ExternalLink", category: "Actions", component: ExternalLinkIcon },
  { name: "Upload", source: "Upload", category: "Actions", component: UploadIcon },
  { name: "Play", source: "Play", category: "Actions", component: PlayIcon },
  { name: "Minus", source: "Minus", category: "Actions", component: MinusIcon },
  { name: "ChevronDown", source: "ChevronDown", category: "Navigation", component: ChevronDownIcon },
  { name: "ChevronRight", source: "ChevronRight", category: "Navigation", component: ChevronRightIcon },
  { name: "ChevronUp", source: "ChevronUp", category: "Navigation", component: ChevronUpIcon },
  { name: "Home", source: "Home", category: "Navigation", component: HomeIcon },
  { name: "Menu", source: "Menu", category: "Navigation", component: MenuIcon },
  { name: "Search", source: "Search", category: "Navigation", component: SearchIcon },
  { name: "Dashboard", source: "LayoutDashboard", category: "Navigation", component: DashboardIcon },
  { name: "Template", source: "LayoutTemplate", category: "Navigation", component: TemplateIcon },
  { name: "Code", source: "Code2", category: "Data & runtime", component: CodeIcon },
  { name: "Database", source: "Database", category: "Data & runtime", component: DatabaseIcon },
  { name: "Tag", source: "Tag", category: "Data & runtime", component: TagIcon },
  { name: "Tags", source: "Tags", category: "Data & runtime", component: TagsIcon },
  { name: "Braces", source: "Braces", category: "Data & runtime", component: BracesIcon },
  { name: "Function", source: "FunctionSquare", category: "Data & runtime", component: FunctionIcon },
  { name: "Cable", source: "Cable", category: "Data & runtime", component: CableIcon },
  { name: "Gauge", source: "Gauge", category: "Data & runtime", component: GaugeIcon },
  { name: "Radio", source: "Radio", category: "Data & runtime", component: RadioIcon },
  { name: "RadioTower", source: "RadioTower", category: "Data & runtime", component: RadioTowerIcon },
  { name: "Activity", source: "Activity", category: "Data & runtime", component: ActivityIcon },
  { name: "Branch", source: "GitBranch", category: "Data & runtime", component: BranchIcon },
  { name: "Workflow", source: "Workflow", category: "Data & runtime", component: WorkflowIcon },
  { name: "Network", source: "Network", category: "Data & runtime", component: NetworkIcon },
  { name: "Cloud", source: "Cloud", category: "Data & runtime", component: CloudIcon },
  { name: "ServerSettings", source: "ServerCog", category: "Data & runtime", component: ServerSettingsIcon },
  { name: "Zap", source: "Zap", category: "Data & runtime", component: ZapIcon },
  { name: "Box", source: "Box", category: "Editor & layout", component: BoxIcon },
  { name: "Boxes", source: "Boxes", category: "Editor & layout", component: BoxesIcon },
  { name: "LayerStack", source: "Layers3", category: "Editor & layout", component: LayerStackIcon },
  { name: "Layers", source: "Layers", category: "Editor & layout", component: LayersIcon },
  { name: "Grid", source: "LayoutGrid", category: "Editor & layout", component: GridIcon },
  { name: "Rows", source: "Rows3", category: "Editor & layout", component: RowsIcon },
  { name: "PanelTop", source: "PanelTop", category: "Editor & layout", component: PanelTopIcon },
  { name: "Rectangle", source: "RectangleHorizontal", category: "Editor & layout", component: RectangleIcon },
  { name: "Maximize", source: "Maximize2", category: "Editor & layout", component: MaximizeIcon },
  { name: "HorizontalResize", source: "MoveHorizontal", category: "Editor & layout", component: HorizontalResizeIcon },
  { name: "VerticalResize", source: "MoveVertical", category: "Editor & layout", component: VerticalResizeIcon },
  { name: "Radius", source: "Radius", category: "Editor & layout", component: RadiusIcon },
  { name: "DragHandle", source: "GripVertical", category: "Editor & layout", component: DragHandleIcon },
  { name: "Pointer", source: "MousePointer2", category: "Editor & layout", component: PointerIcon },
  { name: "PointerClick", source: "MousePointerClick", category: "Editor & layout", component: PointerClickIcon },
  { name: "Palette", source: "Palette", category: "Appearance", component: PaletteIcon },
  { name: "Typography", source: "Type", category: "Appearance", component: TypographyIcon },
  { name: "Theme", source: "SunMoon", category: "Appearance", component: ThemeIcon },
  { name: "Sun", source: "Sun", category: "Appearance", component: SunIcon },
  { name: "Moon", source: "Moon", category: "Appearance", component: MoonIcon },
  { name: "MonitorSettings", source: "MonitorCog", category: "Appearance", component: MonitorSettingsIcon },
  { name: "Image", source: "Image", category: "Media & devices", component: ImageIcon },
  { name: "ImagePlaceholder", source: "ImageIcon", category: "Media & devices", component: ImagePlaceholderIcon },
  { name: "Images", source: "Images", category: "Media & devices", component: ImagesIcon },
  { name: "Monitor", source: "Monitor", category: "Media & devices", component: MonitorIcon },
  { name: "Tablet", source: "Tablet", category: "Media & devices", component: TabletIcon },
  { name: "Smartphone", source: "Smartphone", category: "Media & devices", component: SmartphoneIcon },
  { name: "ChartLine", source: "ChartLine", category: "Media & devices", component: ChartLineIcon },
  { name: "FileText", source: "FileText", category: "Media & devices", component: FileTextIcon },
  { name: "AlertTriangle", source: "AlertTriangle", category: "Status & misc", component: AlertTriangleIcon },
  { name: "Info", source: "Info", category: "Status & misc", component: InfoIcon },
  { name: "Inbox", source: "Inbox", category: "Status & misc", component: InboxIcon },
  { name: "Notification", source: "Bell", category: "Status & misc", component: NotificationIcon },
  { name: "Key", source: "KeyRound", category: "Status & misc", component: KeyIcon },
  { name: "Lock", source: "LockKeyhole", category: "Status & misc", component: LockIcon },
  { name: "Hand", source: "Hand", category: "Status & misc", component: HandIcon },
  { name: "Settings", source: "Settings", category: "Status & misc", component: SettingsIcon },
  { name: "Square", source: "Square", category: "Status & misc", component: SquareIcon },
  { name: "Star", source: "Star", category: "Status & misc", component: StarIcon },
  { name: "Link", source: "Link2", category: "Status & misc", component: LinkIcon },
  { name: "Unlink", source: "Unlink", category: "Status & misc", component: UnlinkIcon },
];
